POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

> {%
    client.global.set("token", response.body.token);
%}

###

POST http://localhost:8081/api/flights/scheduled
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "routeId": 1,
  "aircraftRegistrationNumber": "CS-TST",
  "scheduledDeparture": "2026-06-10T09:00:00",
  "scheduledArrival": "2026-06-10T10:00:00"
}
