@startuml
skinparam monochrome true
skinparam shadowing false

title Diagrama de Sequência: US113 - Consultar Rotas

actor "ATCC" as User
participant ":ControladorAutenticacao" as Auth
participant ":ControladorRota" as Ctrl
participant ":ServicoRota" as Service
participant ":RepositorioRota" as RepoRoute
participant "rota:Rota" as Route <<Raiz do Agregado>>

activate User

User -> Auth : Autenticar Utilizador
activate Auth
Auth --> User : Autenticação Bem-sucedida (Token JWT)
deactivate Auth

User -> Ctrl : obterRotasDoAeroporto(airportIATA)
activate Ctrl

Ctrl -> Service : obterRotasDoAeroporto(airportIATA)
activate Service

    Service -> RepoRoute : procurarPorIataAeroportoOrigem(airportIATA)
    activate RepoRoute
    RepoRoute --> Service : lista<Route>
    deactivate RepoRoute

    Service --> Ctrl : listaRouteDTO / Erro

    Ctrl --> User : Sucesso (200 OK + Lista de Rotas)

    Ctrl --> User : Erro (404 Não Encontrado)

deactivate Service
deactivate Ctrl

User -> Ctrl : obterDetalhesRota(routeId)
activate Ctrl

Ctrl -> Service : obterDetalhesRota(routeId)
activate Service

    Service -> RepoRoute : procurarPorId(routeId)
    activate RepoRoute
    RepoRoute --> Service : rota
    deactivate RepoRoute

    Service --> Ctrl : routeDTO / Erro

    Ctrl --> User : Sucesso (200 OK + Detalhes da Rota + Ligações)

    Ctrl --> User : Erro (404 Não Encontrado)

deactivate Service
deactivate Ctrl
deactivate User
@enduml