POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "backoffice123"
}

### sees the Top 5 most utilized aircraft models based on total flight hours or number of assignments - 1201107

###

@token =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOWVjMDQ0Mi02NjZjLTRiOTEtOTVkNS04ZjNkMTNmYTVhYzEiLCJyb2xlcyI6WyJCQUNLT0ZGSUNFIl0sImlhdCI6MTc4MjA3MzUwMywiZXhwIjoxNzgyMDc3MTAzfQ.OmqNKaGgdsf7fxSr_73vfHk48tWSvyK4UsG4rwnbG38


GET http://localhost:8081/api/catalog/rankings?mode=assignments
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:8081/api/catalog/rankings?mode=flight-hours
Content-Type: application/json
Authorization: Bearer {{token}}