POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ZDFiYmEwYi0xYzE1LTRkYzgtYjJmZS1hNGYzYmQ2YjhlMmUiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE3NzkwNDE5ODMsImV4cCI6MTc3OTA0NTU4M30.r8a6SqqAnupAJY3Ed4-XC-isH0EkjR0xXokwryz_YSo

###
POST http://localhost:8081/api/airports
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "iataCode": "LIS",
  "airportType": "International",
  "name": "Humberto Delgado Airport",
  "status": "OPERATIONAL",
  "location": {
    "city": "Lisbon",
    "longitude": -9.1359,
    "latitude": 38.7742,
    "region": "Lisbon",
    "timezone": "Europe/Lisbon",
    "country": "Portugal"
  },
  "facilities": {
    "terminalCount": 2,
    "services": ["fuel", "maintenance"],
    "gateCount": 48
  },
  "routeDistance": 0.0,
  "runways": [
    {
      "runwayName": "03/21",
      "length": 3805.0,
      "orientation": "NE/SW",
      "status": "OPEN"
    }
  ],
  "certifications": [],
  "contacts": [
    {
      "type": "EMAIL",
      "value": "ops@lis.pt"
    }
  ],
  "airportPhotos": ["https://example.com/lis.jpg"]
}

###
POST http://localhost:8081/api/airports
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "iataCode": "OPO",
  "airportType": "International",
  "name": "Francisco Sa Carneiro Airport",
  "status": "OPERATIONAL",
  "location": {
    "city": "Porto",
    "longitude": -8.6814,
    "latitude": 41.2481,
    "region": "Porto",
    "timezone": "Europe/Lisbon",
    "country": "Portugal"
  },
  "facilities": {
    "terminalCount": 1,
    "services": ["fuel", "maintenance"],
    "gateCount": 35
  },
  "routeDistance": 0.0,
  "runways": [
    {
      "runwayName": "17/35",
      "length": 3480.0,
      "orientation": "N/S",
      "status": "OPEN"
    }
  ],
  "certifications": [],
  "contacts": [
    {
      "type": "EMAIL",
      "value": "ops@opo.pt"
    }
  ],
  "airportPhotos": ["https://example.com/opo.jpg"]
}

###
POST http://localhost:8081/api/routes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "routeName": "LIS-OPO",
  "originIataCode": "LIS",
  "destinationIataCode": "OPO",
  "estimatedFlightTimeHours": 0.9,
  "type": "DIRECT",
  "requirements": {
    "requiredRange": 3200.0,
    "requiredCapacity": 160
  }
}
