@startuml
skinparam monochrome true
skinparam shadowing false

title Diagrama de Sequência do Sistema (SSD) - US111

actor "ATCC" as User
participant ":Sistema" as System

activate User

User -> System : Autenticar Utilizador
activate System
System --> User : Autenticação Bem-sucedida (Token JWT)
deactivate System

User -> System : obterHistoricoRota(routeId)
activate System

    System --> User : Sucesso (200 OK + Dados do Histórico)
    System --> User : Erro (404 Não Encontrado)

deactivate System
deactivate User
@enduml