@startuml
skinparam monochrome true
skinparam shadowing false

title System Sequence Diagram (SSD) - US216

actor "ATCC" as ATCC
participant "System" as SYS

ATCC -> SYS : GET /api/routes/alternatives?origin=LIS&destination=OPO
activate SYS
SYS --> ATCC : 200 OK + Alternative Routes
deactivate SYS
@enduml
