POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

### changes status of an aircraft

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1NTdlNTNkMS1iYjU5LTRhZjItYmFjZS01ZDM3MGI1YzAzYjAiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MjA3Mjg5MCwiZXhwIjoxNzgyMDc2NDkwfQ.u1VDlVDF5nMo33AMuy5_2nFmxpLxzdCKrUtjruSWq_M

###
PATCH http://localhost:8081/api/hangar/aircraft/CS-TU
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "registrationNumber": "CS-TU",
  "availability": "MAINTENANCE"
}