POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

> {%
    client.global.set("token", response.body.token);
%}

###

GET http://localhost:8081/api/routes/alternatives?origin=LIS&destination=OPO
Authorization: Bearer {{token}}
