POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

### gets an aircraft with filters

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1NTdlNTNkMS1iYjU5LTRhZjItYmFjZS01ZDM3MGI1YzAzYjAiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MjA3MzAyMywiZXhwIjoxNzgyMDc2NjIzfQ.pobVwdd-b4hYuBhk_3ojY03KNCSeA-ZpZ6uEUkCrrGY

###
GET http://localhost:8081/api/hangar/aircraft?model=A320&status=MAINTENANCE
Authorization: Bearer {{token}}